var flippingCardList = [
    {
        url:"https://source.unsplash.com/random/285x211",
    title: "creative design",
        categoryName: "Graphic Design",
        category: "cardGraphic",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Graphic Design",
        category: "cardGraphic",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Graphic Design",
        category: "cardGraphic",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Graphic Design",
        category: "cardGraphic",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Graphic Design",
        category: "cardGraphic",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Graphic Design",
        category: "cardGraphic",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Graphic Design",
        category: "cardGraphic",
    },
    {
        url:"https://source.unsplash.com/random/285x21",
        title: "creative design",
        categoryName: "Graphic Design",
        category: "cardGraphic",
    },
    {
        url:"https://source.unsplash.com/random/285x21",
        title: "creative design",
        categoryName: "Graphic Design",
        category: "cardGraphic",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Web Design",
        category: "cardWeb",
    },
    {
        url:"https://source.unsplash.com/random/285x21",
        title: "creative design",
        categoryName: "Web Design",
        category: "cardWeb",
    },{
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Web Design",
        category: "cardWeb",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Web Design",
        category: "cardWeb",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Web Design",
        category: "cardWeb",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Web Design",
        category: "cardWeb",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Web Design",
        category: "cardWeb",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Web Design",
        category: "cardWeb",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Web Design",
        category: "cardWeb",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Landing Pages",
        category: "cardLanding",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Landing Pages",
        category: "cardLanding",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Landing Pages",
        category: "cardLanding",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Landing Pages",
        category: "cardLanding",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Landing Pages",
        category: "cardLanding",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Landing Pages",
        category: "cardLanding",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Landing Pages",
        category: "cardLanding",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Landing Pages",
        category: "cardLanding",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Landing Pages",
        category: "cardLanding",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Landing Pages",
        category: "cardLanding",
    },
    {
        url:"./images/amazingWork/wordpress/wordpress4.jpg",
        title: "creative design",
        categoryName: "Wordpress",
        category: "cardWordpress",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Wordpress",
        category: "cardWordpress",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Wordpress",
        category: "cardWordpress",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Wordpress",
        category: "cardWordpress",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Wordpress",
        category: "cardWordpress",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Wordpress",
        category: "cardWordpress",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Wordpress",
        category: "cardWordpress",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Wordpress",
        category: "cardWordpress",
    },
    {
        url:"https://source.unsplash.com/random/285x211",
        title: "creative design",
        categoryName: "Wordpress",
        category: "cardWordpress",
    },
];
